Repository SOPT-all/35-COLLABORATION-SERVER-CGV, pull requests merged in 2024-11, with the labels that each got.

#2 [setting] 프로젝트 기본 세팅
  .gitignore
  build.gradle
  src/main/java/com/and_sopt/cdsp/api/movie/controller/MovieController.java
  src/main/java/com/and_sopt/cdsp/api/movie/domain/Movie.java
  src/main/java/com/and_sopt/cdsp/api/movie/repository/MovieRepository.java
  src/main/java/com/and_sopt/cdsp/api/movie/service/MovieService.java
  src/main/java/com/and_sopt/cdsp/api/theater/controller/TheaterController.java
  src/main/java/com/and_sopt/cdsp/api/theater/domain/Theater.java
  src/main/java/com/and_sopt/cdsp/api/theater/repository/TheaterRepository.java
  src/main/java/com/and_sopt/cdsp/api/theater/service/TheaterService.java
  src/main/java/com/and_sopt/cdsp/global/common/BaseTimeEntity.java
  src/main/java/com/and_sopt/cdsp/global/exception/BadRequestException.java
  src/main/java/com/and_sopt/cdsp/global/exception/CustomException.java
  src/main/java/com/and_sopt/cdsp/global/exception/GlobalExceptionHandler.java
  src/main/java/com/and_sopt/cdsp/global/exception/ResponseStatusSetterAdvice.java
  src/main/java/com/and_sopt/cdsp/global/response/ApiResponseDto.java
  src/main/java/com/and_sopt/cdsp/global/response/enums/ErrorCode.java
  src/main/java/com/and_sopt/cdsp/global/response/enums/SuccessCode.java
  src/main/resources/application.properties
Labels: settings, 예린

#5 [Feat] 영화 세부 정보 조회 API
  .DS_Store
  .gitignore
  src/main/java/com/and_sopt/cdsp/CdspApplication.java
  src/main/java/com/and_sopt/cdsp/api/movie/controller/MovieController.java
  src/main/java/com/and_sopt/cdsp/api/movie/domain/Movie.java
  src/main/java/com/and_sopt/cdsp/api/movie/dto/MovieDetailDto.java
  src/main/java/com/and_sopt/cdsp/api/movie/repository/MovieRepository.java
  src/main/java/com/and_sopt/cdsp/api/movie/service/MovieService.java
  src/main/java/com/and_sopt/cdsp/api/theater/domain/Theater.java
  src/main/java/com/and_sopt/cdsp/api/ticket/domain/Ticket.java
  src/main/java/com/and_sopt/cdsp/api/ticket/repository/TicketRepository.java
  src/main/java/com/and_sopt/cdsp/global/common/BaseTimeEntity.java
  src/main/java/com/and_sopt/cdsp/global/response/enums/ErrorCode.java
  src/main/java/com/and_sopt/cdsp/global/response/enums/SuccessCode.java
Labels: 지원, feature

#7 [FEAT] 영화관 조회 API
  src/main/java/com/and_sopt/cdsp/api/theater/controller/TheaterController.java
  src/main/java/com/and_sopt/cdsp/api/theater/service/TheaterService.java
  src/main/java/com/and_sopt/cdsp/global/response/enums/SuccessCode.java
Labels: 나연, feature

#9 [feat] 영화 시간표 조회 API 구현
  src/main/java/com/and_sopt/cdsp/api/movie/domain/Movie.java
  src/main/java/com/and_sopt/cdsp/api/movie/repository/MovieRepository.java
  src/main/java/com/and_sopt/cdsp/api/theater/controller/TheaterController.java
  src/main/java/com/and_sopt/cdsp/api/theater/dto/response/MovieTimelineGetResponse.java
  src/main/java/com/and_sopt/cdsp/api/theater/service/TheaterService.java
  src/main/java/com/and_sopt/cdsp/api/ticket/domain/Ticket.java
  src/main/java/com/and_sopt/cdsp/global/response/enums/ErrorCode.java
Labels: feature, 예린

#11 [Feat] 영화 예매 api 구현
  build.gradle
  src/main/java/com/and_sopt/cdsp/api/movie/controller/MovieController.java
  src/main/java/com/and_sopt/cdsp/api/movie/domain/Movie.java
  src/main/java/com/and_sopt/cdsp/api/movie/dto/MovieBookingDto.java
  src/main/java/com/and_sopt/cdsp/api/movie/repository/MovieRepository.java
  src/main/java/com/and_sopt/cdsp/api/movie/service/MovieService.java
  src/main/java/com/and_sopt/cdsp/api/ticket/domain/Ticket.java
  src/main/java/com/and_sopt/cdsp/global/response/enums/SuccessCode.java
Labels: 나연, feature

#12 [REFACTOR] 영화관 조회 API Dto 생성
  src/main/java/com/and_sopt/cdsp/api/theater/controller/TheaterController.java
  src/main/java/com/and_sopt/cdsp/api/theater/dto/response/MovieTheaterDto.java
  src/main/java/com/and_sopt/cdsp/api/theater/service/TheaterService.java
Labels: 나연, refactor
